# fly.toml file generated for nyx on 2023-04-19T13:05:51+08:00

app = "nyx"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[deploy]
  #release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "nyx.fly.dev"
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[metrics]
  path = "/metrics"
  port = 3927

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 888
    soft_limit = 500
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "20s"
    restart_limit = 5
    timeout = "10s"
