version: "3.8"
services:
  heimdallr:
    build: ./HeimdallrNode/
    ports:
      - "80:5000"
    links:
      - "mercury:flask"
    env_file:
      - .env
    restart: always
  wolfsmoke:
    build: ./WolfSmoke/
    volumes:
      - ./WolfSmoke/src:/home/wolf/src/
      - ./WolfSmoke/shard:/home/wolf/shard:rw
    restart: always
    env_file:
      - .env
