version: "3.8"
services:
  heimdallr:
    build: ./HeimdallrNode/
    ports:
      - "80:5000"
    links:
      - "mercury:flask"
    env_file:
      - .env
    restart: always
  mercury:
    build: ./MercuryFlask/
    volumes:
      - ./MercuryFlask:/usr/src/mercury
    restart: always
    env_file:
      - .env
  wolfsmoke:
    build: ./WolfSmoke/
    volumes:
      - ./WolfSmoke/src:/home/wolf/src/
      - ./WolfSmoke/shardState.json:/home/wolf/shardState.json:rw
    restart: always
    env_file:
      -.env
