version: "3.8"
services:
  heimdallr:
    build: ./HeimdallrNode/
    volumes:
      - ./HeimdallrNode:/usr/src/heimdallr
    ports:
      - "5000:5000"
    depends_on:
      - dynamodb
      - localstack
    links:
      - "dynamodb:database"
      - "localstack:s3"
  localstack:
    image: localstack/localstack-full:latest
    volumes:
      - ./.localstack:/tmp/localstack
    ports:
      - "3000:4566"
      - "3001:41629"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    
