version: "3.8"
services:
  heimdallr:
    build: ./HeimdallrNode/
    ports:
      - "80:5000"
    links:
      - "mercury:flask"
    environment:
      - DEBUG=1
    env_file:
      - .env      
  mercury:
    build: ./MercuryFlask/
    volumes:
      - ./MercuryFlask:/usr/src/mercury
    restart: always
    environment:
      - DEBUG=1
    env_file:
      - .env
 
