version: "3.8"
services:
  heimdallr:
    build: ./HeimdallrNode/
    volumes:
      - ./HeimdallrNode:/home/node/heimdallr
      - /home/node_modules/
      - ~/.aws/:/root/.aws:ro
    ports:
      - "5000:5000"
      - "9229:9229"
    depends_on:
      - dynamodb
    links:
      - "dynamodb:database"
    command:
      - npx
      - nodemon
      - "--inspect-brk=0.0.0.0"
      - "."
    env_file:
      - .env
    

  localstack:
    image: localstack/localstack-full:latest
    volumes:
      - ./.localstack:/tmp/localstack
    ports:
      - "3000:4566"
      - "3001:41629"
      - "8080:8080"
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  mercury:
    build: ./MercuryFlask/
    volumes:
      - ./MercuryFlask:/usr/src/mercury
    ports:
      - "7000:3000"
    depends_on:
      - dynamodb
    links:
      - "dynamodb:database"
    restart: always
    env_file:
      - .env
