version: "3.8"
services:
  heimdallr:
    build: ./HeimdallrNode/
    volumes:
      - ./HeimdallrNode:/home/node/heimdallr
      - /home/node/heimdallr/node_modules
      - ~/.aws/:/root/.aws:ro
    ports:
      - "5000:5000"
      - "9229:9229"
    depends_on:
      - dynamodb
    links:
      - "dynamodb:database"
    command:
      - npx
      - nodemon
      - "--inspect-brk=0.0.0.0"
      - "."
    env_file:
      - .env
    

  localstack:
    image: localstack/localstack:0.12.12
    volumes:
      - ./.localstack:/tmp/localstack
      - ./.localstack/ses:/tmp/localstack/data/ses
      - ./.localstack/setup.sh:/docker-entrypoint-initaws.d
    ports:
      - "3000:4566"
      - "3001:41629"
      - "8080:8080"
      - "4579:4579"
    environment:
      - SERVICES=s3,sqs,ses
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data

  dynamodb:
    build: ./Dyna/
    ports:
      - "8000:8000"

  mercury:
    build: ./MercuryFlask/
    volumes:
      - ./MercuryFlask:/usr/src/mercury
    ports:
      - "7000:3000"
    depends_on:
      - dynamodb
    links:
      - "dynamodb:database"
    restart: always
    env_file:
      - .env

  wolfsmoke:
    build: ./WolfSmoke
    command: npm run debug
    volumes:
      - ./WolfSmoke/dist/src:/usr/src/wolf/dist/src/
    ports:
      - "5001:3001"
      - "9222:9222"
    depends_on:
      - dynamodb
    links:
      - "dynamodb:database"
    restart: always
    env_file:
      - .env
