version: "3.8"
services:
  heimdallr:
    build: ./HeimdallrNode/
    volumes:
      - ./HeimdallrNode:/home/node/heimdallr
      - /home/node/heimdallr/node_modules
      - ~/.aws/:/root/.aws:ro
    ports:
      - "5000:5000"
      - "9229:9229"
    depends_on:
      - dynamodb
    links:
      - "dynamodb:database"
    command:
      - npx
      - nodemon
      - "--inspect-brk=0.0.0.0"
      - "."
    env_file:
      - .env

  dynamodb:
    build:
      context: ./Dyna/
      dockerfile: ARMyfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Singapore

  wolfsmoke:
    build:
      context: ./WolfSmoke
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./WolfSmoke/src:/home/wolf/src/
      - ./WolfSmoke/nodemon.json:/home/wolf/nodemon.json
      - ./WolfSmoke/shard:/home/wolf/shard:rw
    ports:
      - "9222:9222"
    depends_on:
      dynamodb:
        condition: service_healthy
    links:
      - "dynamodb:database"
    command:
      - npx
      - nodemon
      - "src/index.ts"
    env_file:
      - .env
