app = "loki"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[mount]
  source = "loki_storage"
  destination = "/data/loki"

[env]

[[services]]
  internal_port = 3100
  protocol = "tcp"

[services.concurrency]
  hard_limit = 25
  soft_limit = 20

[[services.ports]]
  handlers = ["http"]
  port = 80
